import { describe, it, expect, beforeEach } from 'bun:test';
import { faker } from '@faker-js/faker';
import { KvEncryptionRot13 } from './kv-encryption-rot13';

const enc = new TextEncoder();
const dec = new TextDecoder();

describe('KvEncryptionRot13', () => {
    let rot: KvEncryptionRot13;
    let blockId: number;

    beforeEach(() => {
        rot = new KvEncryptionRot13();
        blockId = faker.number.int(100);
    });

    // Hard-coded vectors generated by `scripts/generate-encryption-vectors.mjs`
    // (run with raw Node, not Bun, so the reference is anchored to a
    // standalone implementation independent of this codebase).
    describe('hard-coded vector', () => {
        const PLAINTEXT_HEX = '48656c6c6f2c20576f726c64212031323334'; // "Hello, World! 1234"
        const CIPHERTEXT_HEX = '55727979622c204a62657971212031323334'; // "Uryyb, Jbeyq! 1234"

        function fromHex(hex: string): Uint8Array {
            return new Uint8Array(hex.match(/.{2}/g)!.map((b) => parseInt(b, 16)));
        }
        function toHex(bytes: Uint8Array): string {
            return Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
        }

        it('encrypts a known plaintext to the expected ciphertext bytes', async () => {
            const out = await rot.encrypt(blockId, fromHex(PLAINTEXT_HEX));
            expect(toHex(out)).toBe(CIPHERTEXT_HEX);
        });

        it('decrypts a known ciphertext to the expected plaintext bytes', async () => {
            const out = await rot.decrypt(blockId, fromHex(CIPHERTEXT_HEX));
            expect(toHex(out)).toBe(PLAINTEXT_HEX);
        });
    });

    describe('encrypt', () => {
        it('shifts uppercase A-M to N-Z', async () => {
            const result = await rot.encrypt(blockId, enc.encode('ABCDEFGHIJKLM'));
            expect(dec.decode(result)).toBe('NOPQRSTUVWXYZ');
        });

        it('shifts uppercase N-Z back to A-M (wrap-around)', async () => {
            const result = await rot.encrypt(blockId, enc.encode('NOPQRSTUVWXYZ'));
            expect(dec.decode(result)).toBe('ABCDEFGHIJKLM');
        });

        it('shifts lowercase a-m to n-z', async () => {
            const result = await rot.encrypt(blockId, enc.encode('abcdefghijklm'));
            expect(dec.decode(result)).toBe('nopqrstuvwxyz');
        });

        it('shifts lowercase n-z back to a-m (wrap-around)', async () => {
            const result = await rot.encrypt(blockId, enc.encode('nopqrstuvwxyz'));
            expect(dec.decode(result)).toBe('abcdefghijklm');
        });

        it('preserves case (uppercase stays uppercase, lowercase stays lowercase)', async () => {
            const result = await rot.encrypt(blockId, enc.encode('Hello, World!'));
            expect(dec.decode(result)).toBe('Uryyb, Jbeyq!');
        });

        it('passes through non-letter ASCII bytes (digits, punctuation, whitespace)', async () => {
            const input = enc.encode('0123 !@#$%^&*()_+-=[]{}|;:",.<>/?\t\n');
            const result = await rot.encrypt(blockId, input);
            expect(Array.from(result)).toEqual(Array.from(input));
        });

        it('passes through bytes outside the ASCII letter ranges', async () => {
            // 0x00-0x40 (before 'A'), 0x5B-0x60 (between 'Z' and 'a'),
            // 0x7B-0xFF (after 'z') must all pass through unchanged.
            const input = new Uint8Array(256);
            for (let i = 0; i < 256; i++) input[i] = i;

            const result = await rot.encrypt(blockId, input);

            for (let i = 0; i < 256; i++) {
                const isUpper = i >= 0x41 && i <= 0x5a;
                const isLower = i >= 0x61 && i <= 0x7a;
                if (isUpper || isLower) {
                    expect(result[i]).not.toBe(i);
                } else {
                    expect(result[i]).toBe(i);
                }
            }
        });

        it('preserves byte length', async () => {
            const input = new Uint8Array(faker.number.int({ min: 0, max: 10_000 }));
            for (let i = 0; i < input.length; i++) input[i] = i & 0xff;

            const result = await rot.encrypt(blockId, input);

            expect(result.length).toBe(input.length);
        });

        it('returns an empty buffer for empty input', async () => {
            const result = await rot.encrypt(blockId, new Uint8Array(0));

            expect(result).toBeInstanceOf(Uint8Array);
            expect(result.length).toBe(0);
        });

        it('returns a fresh buffer (does not mutate the input)', async () => {
            const input = enc.encode('hello');
            const inputSnapshot = Array.from(input);

            const result = await rot.encrypt(blockId, input);

            expect(result).not.toBe(input);
            expect(Array.from(input)).toEqual(inputSnapshot);
        });
    });

    describe('decrypt', () => {
        it('reverses encrypt for letters', async () => {
            const original = enc.encode('Hello, World!');
            const encrypted = await rot.encrypt(blockId, original);

            const decrypted = await rot.decrypt(blockId, encrypted);

            expect(dec.decode(decrypted)).toBe('Hello, World!');
        });

        it('produces the same output as encrypt (ROT13 is self-inverse)', async () => {
            const input = enc.encode(faker.lorem.paragraph());

            const encrypted = await rot.encrypt(blockId, input);
            const decrypted = await rot.decrypt(blockId, input);

            expect(Array.from(encrypted)).toEqual(Array.from(decrypted));
        });
    });

    describe('round-trip', () => {
        it.each([
            'hello',
            'HELLO',
            'Mixed CASE 1234',
            '',
            'Uryyb, Jbeyq!', // already-encoded text
            'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
            'The quick brown fox jumps over the lazy dog.',
        ])('encrypt -> decrypt restores %j', async (text) => {
            const original = enc.encode(text);

            const encrypted = await rot.encrypt(blockId, original);
            const decrypted = await rot.decrypt(blockId, encrypted);

            expect(dec.decode(decrypted)).toBe(text);
        });

        it('encrypt twice returns the original (self-inverse identity)', async () => {
            const original = enc.encode('Lorem ipsum dolor sit amet.');

            const once = await rot.encrypt(blockId, original);
            const twice = await rot.encrypt(blockId, once);

            expect(Array.from(twice)).toEqual(Array.from(original));
        });

        it('round-trips arbitrary binary content (full 0..255 byte range)', async () => {
            const input = new Uint8Array(256);
            for (let i = 0; i < 256; i++) input[i] = i;

            const encrypted = await rot.encrypt(blockId, input);
            const decrypted = await rot.decrypt(blockId, encrypted);

            expect(Array.from(decrypted)).toEqual(Array.from(input));
        });

        it('round-trips a random-byte payload', async () => {
            const input = new Uint8Array(4096);
            for (let i = 0; i < input.length; i++) {
                input[i] = faker.number.int({ min: 0, max: 255 });
            }

            const encrypted = await rot.encrypt(blockId, input);
            const decrypted = await rot.decrypt(blockId, encrypted);

            expect(Array.from(decrypted)).toEqual(Array.from(input));
        });
    });

    describe('shift correctness', () => {
        it('shifts each ASCII letter by exactly 13 positions', async () => {
            for (let i = 0; i < 26; i++) {
                const upperPlain = String.fromCharCode(0x41 + i);
                const lowerPlain = String.fromCharCode(0x61 + i);
                const expectedUpper = String.fromCharCode(0x41 + ((i + 13) % 26));
                const expectedLower = String.fromCharCode(0x61 + ((i + 13) % 26));

                const upperResult = await rot.encrypt(blockId, enc.encode(upperPlain));
                const lowerResult = await rot.encrypt(blockId, enc.encode(lowerPlain));

                expect(dec.decode(upperResult)).toBe(expectedUpper);
                expect(dec.decode(lowerResult)).toBe(expectedLower);
            }
        });
    });
});
